# Generated by Django 2.0.5 on 2018-05-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinacion.Coordinacion', verbose_name='Coordinación'),
        ),
    ]
