# Generated by Django 2.0.5 on 2018-06-11 00:39

import asignaturas.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0001_initial'),
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveIntegerField(choices=[(0, 'Enero - Marzo'), (1, 'Abril - Julio'), (2, 'Septiembre - Diciembre')], verbose_name='Trimestre de la oferta')),
                ('anio', models.PositiveIntegerField(validators=[asignaturas.models.anio_oferta_valido], verbose_name='Año de la oferta')),
                ('coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='coordinacion.Coordinacion', verbose_name='Coordinacion')),
            ],
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codasig',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='codigo_invalido', message='Formato de código incorrecto. Ej: CO3121', regex='^[A-Z]{2}[0-9]{4}$')], verbose_name='Código de Asignatura'),
        ),
        migrations.AlterField(
            model_name='programaasignatura',
            name='url',
            field=models.CharField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Código de Programa'),
        ),
    ]
