# Generated by Django 2.0.5 on 2018-05-25 03:24

import asignaturas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0003_auto_20180522_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_final',
            field=models.PositiveIntegerField(validators=[asignaturas.models.hora_valida], verbose_name='Hora Final'),
        ),
    ]
