# Generated by Django 2.0.5 on 2018-05-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0004_auto_20180525_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaasignatura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programaasignatura',
            name='url',
            field=models.URLField(default='usb.ve', unique=True, verbose_name='Código de Programa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='programaasignatura',
            unique_together={('url', 'asignatura')},
        ),
    ]
