# Generated by Django 2.0.5 on 2018-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0005_auto_20180531_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codasig',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código de Asignatura'),
        ),
    ]
