# Generated by Django 2.0.5 on 2018-05-31 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0009_auto_20180531_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='fecha_de_ejecucion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de ejecución'),
        ),
    ]
