# Generated by Django 2.0.5 on 2018-05-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0010_asignatura_fecha_de_ejecucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='vista',
            field=models.BooleanField(default=False, verbose_name='Vista'),
        ),
    ]
