# Generated by Django 2.0.5 on 2018-06-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0011_asignatura_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='vista',
            field=models.BooleanField(default=False, verbose_name='Asignatura Vista'),
        ),
    ]
