language: python
addons:
  firefox: latest
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - ./install.sh
script:
  - xvfb-run --server-args="-screen 0 1366x768x24" python manage.py test
