# Generated by Django 2.0.5 on 2018-06-15 12:07

from django.db import migrations, models
import oferta.models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0001_initial'),
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='anio',
            field=models.PositiveIntegerField(validators=[oferta.models.anio_oferta_valido], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='trimestre',
            field=models.PositiveIntegerField(choices=[(0, 'Enero - Marzo'), (1, 'Abril - Julio'), (2, 'Septiembre - Diciembre')], verbose_name='Trimestre'),
        ),
        migrations.AlterUniqueTogether(
            name='oferta',
            unique_together={('trimestre', 'anio', 'coordinacion')},
        ),
    ]
