# Generated by Django 2.0.5 on 2018-06-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_auto_20180615_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='anio',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
    ]
