# Generated by Django 2.0.5 on 2018-06-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_auto_20180611_0113'),
        ('oferta', '0003_auto_20180618_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='asignatura',
            field=models.ManyToManyField(related_name='ofertas', to='asignaturas.Asignatura', verbose_name='Asignatura'),
        ),
    ]
