# Generated by Django 2.0.5 on 2018-05-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='primer_appelido',
            new_name='primer_apellido',
        ),
    ]
